### ISSUE TITLE
Add LICENSE to repo

### ISSUE THREAD

**Issue by apollo-pacman** [apollodao/cw-vault-token#27]
### DoD

- Add a LICENSE file
- Update `deny.toml` file.

> yes, since we dont have any license file I set up for now to continue and dont break the checks. Once we add the LICENSE file, it should be turn to false.

_Originally posted by @apollo-pablo in https://github.com/apollodao/cw-token/pull/18#discussion_r1016247874_

**Comment by apollo-sturdy** [comment]
We either need to use GPL or remove `cw-asset` as a dependency. I suggest removing it and using MPL.
