### ISSUE TITLE
Enhancement for docs

### ISSUE THREAD

**Issue by apollo-pablo** [apollodao/cw-vault-token#33]
> Research on `rustfmt.toml` 

```
format_code_in_doc_comments = true
wrap_comments = true
```

> Tasks:
- [x] Add a cargo make task.

> Note:

Its need cargo-make installed `cargo install --no-default-features --force cargo-make`

**Comment by apollo-pacman** [comment]
I know these features require nighly and I dont want to run nightly in CI. but I think if we can have a separate `nightly_rustfmt.toml` file that we use when we run `make format` locally but not in CI that would be great

**Comment by apollo-pacman** [comment]
closed by #47
